[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "Collection of common types and imports used in the matrix-sdk"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-common"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version = "1.56"
version = "0.4.1"

[dependencies]
async-trait = "0.1.50"
serde = "1.0.126"

[dependencies.ruma]
git = "https://github.com/ruma/ruma/"
rev = "fdbc4d6d1dd273c8a6ac95b329943ed8c68df70d"
features = ["client-api-c"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "0.8.2", default-features = false, features = [
    "v4",
    "serde",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1.7.1"
default-features = false
features = ["rt", "sync"]

[target.'cfg(target_arch = "wasm32")'.dependencies.instant]
version = "0.1.9"
features = ["wasm-bindgen", "now"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.instant]
version = "0.1.9"
features = ["now"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-lock = "2.4.0"
futures-util = { version = "0.3.15", default-features = false, features = ["channel"] }
wasm-bindgen-futures = "0.4.24"
uuid = { version = "0.8.2", default-features = false, features = [
    "v4",
    "wasm-bindgen",
    "serde",
] }
