[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "Matrix encryption library"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-crypto"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version = "1.56"
version = "0.4.1"

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
default = ["backups_v1"]
qrcode = ["matrix-qrcode"]
backups_v1 = []
sled_cryptostore = ["sled"]
docs = ["sled_cryptostore"]

[dependencies]
aes = { version = "0.7.4", features = ["ctr"] }
aes-gcm = "0.9.2"
atomic = "0.5.0"
base64 = "0.13.0"
bs58 = "0.4.0"
byteorder = "1.4.3"
dashmap = "4.0.2"
futures-util = { version = "0.3.15", default-features = false }
getrandom = "0.2.3"
hmac = "0.11.0"
matrix-qrcode = { version = "0.2.0", path = "../matrix-qrcode", optional = true }
matrix-sdk-common = { version = "0.4.0", path = "../matrix-sdk-common" }
olm-rs = { features = ["serde"], path = "/home/poljar/werk/priv/olm-rs" }
pbkdf2 = { version = "0.9.0", default-features = false }
rand = "0.8.4"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0.64"
sha2 = "0.9.5"
sled = { version = "0.34.6", optional = true }
thiserror = "1.0.25"
tracing = "0.1.26"
zeroize = { version = "1.3.0", features = ["zeroize_derive"] }

[dependencies.ruma]
git = "https://github.com/ruma/ruma/"
rev = "fdbc4d6d1dd273c8a6ac95b329943ed8c68df70d"
features = ["client-api-c", "unstable-pre-spec"]

[dev-dependencies]
criterion = { version = "0.3.4", features = [
    "async",
    "async_tokio",
    "html_reports",
] }
futures = { version = "0.3.15", default-features = false, features = ["executor"] }
http = "0.2.4"
indoc = "1.0.3"
matches = "0.1.8"
matrix-sdk-test = { version = "0.4.0", path = "../matrix-sdk-test" }
proptest = "1.0.0"
serde_json = "1.0.64"
tempfile = "3.2.0"
tokio = { version = "1.7.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
pprof = { version = "0.5.0", features = ["flamegraph", "criterion"] }

[[bench]]
name = "crypto_bench"
harness = false
required-features = ["sled_cryptostore"]
