[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "The base component to build a Matrix client library."
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-base"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version = "1.56"
version = "0.4.1"

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[features]
default = []
encryption = ["matrix-sdk-crypto"]
qrcode = ["matrix-sdk-crypto/qrcode"]
sled_state_store = [
    "sled",
    "pbkdf2",
    "hmac",
    "sha2",
    "rand",
    "chacha20poly1305",
]
sled_cryptostore = ["matrix-sdk-crypto/sled_cryptostore"]

docs = ["encryption", "sled_cryptostore"]

[dependencies]
chacha20poly1305 = { version = "0.9.0", optional = true }
dashmap = "4.0.2"
futures-core = "0.3.15"
futures-util = { version = "0.3.15", default-features = false }
hmac = { version = "0.11.0", optional = true }
lru = "0.6.5"
matrix-sdk-common = { version = "0.4.0", path = "../matrix-sdk-common" }
matrix-sdk-crypto = { version = "0.4.0", path = "../matrix-sdk-crypto", optional = true }
pbkdf2 = { version = "0.9.0", default-features = false, optional = true }
rand = { version = "0.8.4", optional = true }
serde = { version = "1.0.126", features = ["rc"] }
serde_json = "1.0.64"
sha2 = { version = "0.9.5", optional = true }
sled = { version = "0.34.6", optional = true }
thiserror = "1.0.25"
tracing = "0.1.26"
zeroize = { version = "1.3.0", features = ["zeroize_derive"] }

[dependencies.ruma]
git = "https://github.com/ruma/ruma/"
rev = "fdbc4d6d1dd273c8a6ac95b329943ed8c68df70d"
features = ["client-api-c", "unstable-pre-spec"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1.7.1"
default-features = false
features = ["sync", "fs"]

[dev-dependencies]
futures = { version = "0.3.15", default-features = false, features = ["executor"] }
http = "0.2.4"
matrix-sdk-test = { version = "0.4.0", path = "../matrix-sdk-test" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
atty = "0.2.14"
clap = "2.33.3"
rustyline = "9.0.0"
rustyline-derive = "0.5.0"
syntect = "4.5.0"
tokio = { version = "1.7.1", default-features = false, features = [
    "rt-multi-thread",
    "macros",
] }
tempfile = "3.2.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.24"

[[example]]
name = "state_inspector"
required-features = ["sled_state_store"]
